@startuml ants
class Pool {
    workerArray workers
    state
    + NewPool()
    + Submit()
    + Free()
    + Cap()
    + Release()
    + Reboot()
}

class goWorker {
    Pool pool
    task
    -run()
}

interface workerArray{
    -len() int
	-isEmpty() bool
	-insert(worker *goWorker) error
	-detach() *goWorker
	-retrieveExpiry(duration time.Duration) []*goWorker
	-reset()
}

class loopQueue{
    goWorker[] goWorker
}
class workerStack{
    goWorker[] goWorker
}

Pool <-- goWorker
Pool -> workerArray

workerArray <|-- loopQueue
workerArray <|-- workerStack

loopQueue o-- goWorker
workerStack o-- goWorker

@enduml
